### ISSUE TITLE
iOS linking not working

### ISSUE THREAD

**Issue by e-nouri** [miyabi/react-native-passkit-wallet#1]
installed it on with yarn and when i tried to import the xcode project, xcode complains because it cannot open the project file, any help ?

**Comment by miyabi** [comment]
@e-nouri  I'm sorry, it's my fault!
I noticed that the project file's compatibility version was 9.3 (still beta).
Now I fixed it and released v0.1.2.
Please try it.

**Comment by milesmatthias** [comment]
@miyabi it's the same issue for Android as well

**Comment by miyabi** [comment]
@milesmatthias I just fixed for Android and released v0.1.3. Please try this.
