### ISSUE TITLE
ANDROID: "unknown:ReactNative: com.facebook.react.bridge.NativeArgumentsParseException: RNPassKit.addPass got 3 arguments, expected 4"

### ISSUE THREAD

**Issue by danielrybakov** [miyabi/react-native-passkit-wallet#10]
Hello, I have systematically a crash when using with Android after checking that the method "canAddPass" from the library returns true.

React Native version : 0.59.8

I added the last version of this library (not released yet), here is the realted line in my package.json:

"react-native-passkit-wallet": "git://github.com/miyabi/react-native-passkit-wallet.git"

06-03 11:20:11.490 26956 27045 E unknown:ReactNative: Exception in native call
06-03 11:20:11.490 26956 27045 E unknown:ReactNative: com.facebook.react.bridge.NativeArgumentsParseException: RNPassKit.addPass got 3 arguments, expected 4
06-03 11:20:11.490 26956 27045 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:353)
06-03 11:20:11.490 26956 27045 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
06-03 11:20:11.490 26956 27045 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-03 11:20:11.490 26956 27045 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:790)
06-03 11:20:11.490 26956 27045 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-03 11:20:11.490 26956 27045 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
06-03 11:20:11.490 26956 27045 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:164)
06-03 11:20:11.490 26956 27045 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:232)
06-03 11:20:11.490 26956 27045 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:764)

Can you help me with this please ?

Thank you

**Comment by miyabi** [comment]
For Android, file provider has to be specified for the second argument of addPass.
