### ISSUE TITLE
Add to pass button?

### ISSUE THREAD

**Issue by milesmatthias** [miyabi/react-native-passkit-wallet#2]
The add to pass button does not include the standard Apple image. The documentation does not show what values you have for `{styles.addPassButton}`

I have these styles and I can't see any wallet image on the button: 

```
	addPassButton: {
		marginTop: 100,
		height: PassKit.AddPassButtonHeight,
		width: PassKit.AddPassButtonWidth
	}
```

**Comment by miyabi** [comment]
Could you give more information about your environment?
The wallet image doesn't appear while running app on simulator, but it appears on device.
(I don't know why)

**Comment by milesmatthias** [comment]
You're right about the simulator, thanks.
