### ISSUE TITLE
How to create custom.pkpass file

### ISSUE THREAD

**Issue by Dhvani-Impero** [miyabi/react-native-passkit-wallet#28]

**Comment by purevsurena** [comment]
Ensure that the backend is equipped to handle the management and generation of pkpass files, followed by a seamless upload to a designated cloud storage system. 

To generate on your backend, utilize the following library: [passkit-generator](https://www.npmjs.com/package/passkit-generator). 

For React Native, consider using [react-native-wallet-manager](https://www.npmjs.com/package/react-native-wallet-manager).

Here's an overview of the underlying logic:
![photo_6071082980845140606_w](https://github.com/miyabi/react-native-passkit-wallet/assets/35187128/cdce3529-6ed8-4448-be57-59cfab2db851)

**Comment by Dhvani-Impero** [comment]
Thanks !!
