### ISSUE TITLE
Expanded example?

### ISSUE THREAD

**Issue by milesmatthias** [miyabi/react-native-passkit-wallet#3]
Can you expand on how a pass should be added? The example in the README is simply:

```js
PassKit.addPass(base64EncodedPass)
```

Does this mean that we should generate a signed pass (ending in `.pkpass`) and then base64 encode that file's contents?

I've tried that only to get a generic "Adding pass error".

**Comment by milesmatthias** [comment]
I finally got this working. The issue here was that when you do the base64 encoding of the file's contents, it places newline characters into the encoding. Removing all the newlines to get one continuous string of base64 encoded `.pkpass` file contents allowed this to work.

**Comment by VamshiKyra** [comment]
@milesmatthias  Would you able to show the piece of code where you generate .pkpass file. 

YellowBox.js:67 Possible Unhandled Promise Rejection (id: 3):
Error: Failed to create pass.

This is my error

**Comment by nikunjg** [comment]
same here, I am getting this error - YellowBox.js:67 Possible Unhandled Promise Rejection (id: 3):
Error: Failed to create pass.

This is my error

**Comment by saeedtkh** [comment]
Does any body knows how should I call the x.pkpass file in react-native file?
Should I convert it to base64 (Using this react-native-base64) and then pass it to PassKit.addPass()? I am in the right track?
I really appreciate any help.

**Comment by ylevytskyi** [comment]
You can use rn-fetch-blob

 RNFetchBlob.fetch('GET', 'https://welbes-shared.s3.amazonaws.com/williamwelbes.pkpass').then((res) => {
    let base64Str = res.base64();
    PassKit.addPass(base64Str)
});

**Comment by kurnal** [comment]
@milesmatthias @VamshiKyra can someone explain how to create a pass file to begin with
