### ISSUE TITLE
Package is either out of date or not working

### ISSUE THREAD

**Issue by ernst77** [miyabi/react-native-passkit-wallet#8]
Hello,

It seems that the package is not working on iOS, either the instructions are not fully documented or package is out of date :/

**Comment by niallobrien** [comment]
Any update on this?

**Comment by miyabi** [comment]
I'm sorry, I haven't release new version yet, but you can try the current master branch like this:

```
npm i --save react-native-passkit-wallet@git://github.com/miyabi/react-native-passkit-wallet.git
```

By the way, I will release new version soon.
